Repository KUIT-MAPU/MAPU-Backend, pull requests merged in 2024-08, with the labels that each got.

#55 Feat(Map): add map domain
  src/main/java/com/mapu/domain/map/api/MapController.java
  src/main/java/com/mapu/domain/map/application/MapService.java
  src/main/java/com/mapu/domain/map/application/response/MapListResponseDTO.java
  src/main/java/com/mapu/domain/map/application/response/MapOwnerResponseDTO.java
  src/main/java/com/mapu/domain/map/dao/MapKeywordRepository.java
  src/main/java/com/mapu/domain/map/dao/MapRespository.java
  src/main/java/com/mapu/domain/map/domain/Keyword.java
  src/main/java/com/mapu/domain/map/domain/Map.java
  src/main/java/com/mapu/domain/map/domain/MapKeyword.java
  src/main/java/com/mapu/domain/map/exception/MapException.java
  src/main/java/com/mapu/domain/map/exception/errcode/MapExceptionErrorCode.java
  src/main/java/com/mapu/domain/map/exception/handler/MapExceptionHandler.java
  src/main/java/com/mapu/domain/user/api/UserController.java
  src/main/java/com/mapu/domain/user/application/UserService.java
  src/main/java/com/mapu/domain/user/dao/UserRepository.java
  src/main/java/com/mapu/domain/user/domain/UserStatus.java
  src/main/java/com/mapu/global/common/config/SecurityConfig.java
  src/main/java/com/mapu/global/jwt/filter/JwtFilter.java
  src/main/java/com/mapu/infra/oauth/application/OAuthService.java
  src/main/java/com/mapu/infra/oauth/config/OAuthClientConfig.java
  src/main/java/com/mapu/infra/oauth/dao/OAuthRepository.java
  src/main/java/com/mapu/infra/oauth/google/GoogleUserService.java
  src/main/java/com/mapu/infra/oauth/kakao/KakaoUserService.java
  src/main/resources/application.yml
Labels: 🛠 Feature

#56 Feat: 10일간 로그 파일 저장
  src/main/resources/logback-spring.xml
  src/main/resources/logback-variables.properties
Labels: 🛠 Feature

#58 Feat(domain): domain 완료
  src/main/java/com/mapu/domain/figure/api/FigureController.java
  src/main/java/com/mapu/domain/figure/application/FigureService.java
  src/main/java/com/mapu/domain/figure/application/response/FigureResponseDTO.java
  src/main/java/com/mapu/domain/figure/dao/FigureRepository.java
  src/main/java/com/mapu/domain/figure/domain/Figure.java
  src/main/java/com/mapu/domain/figure/domain/FigureRate.java
  src/main/java/com/mapu/domain/figure/domain/FigureRelation.java
  src/main/java/com/mapu/domain/figure/domain/FigureTag.java
  src/main/java/com/mapu/domain/figure/domain/FigureType.java
  src/main/java/com/mapu/domain/figure/domain/FirgureVertex.java
  src/main/java/com/mapu/domain/figure/exception/FigureException.java
  src/main/java/com/mapu/domain/map/api/HomeController.java
  src/main/java/com/mapu/domain/map/api/MapController.java
  src/main/java/com/mapu/domain/map/api/request/CreateMapRequestDTO.java
  src/main/java/com/mapu/domain/map/application/MapService.java
  src/main/java/com/mapu/domain/map/domain/Map.java
  src/main/java/com/mapu/domain/map/domain/MapUserRole.java
  src/main/java/com/mapu/domain/map/domain/Role.java
  src/main/java/com/mapu/global/common/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🛠 Feature

#64 Fix(Map): search Api paging 오류 & dev branch merge 오류
  src/main/java/com/mapu/domain/map/api/MapController.java
  src/main/java/com/mapu/domain/map/application/MapService.java
  src/main/java/com/mapu/domain/map/dao/MapKeywordRepository.java
  src/main/java/com/mapu/domain/map/dao/MapRepository.java
Labels: ✔Fix

#65 Feat: 공동편집자 조회 및 추가 기능 구현
  logback-spring.xml
  logback-variables.properties
  src/main/java/com/mapu/domain/follow/dao/FollowRepository.java
  src/main/java/com/mapu/domain/map/api/MapController.java
  src/main/java/com/mapu/domain/map/api/request/AddEditorRequestDTO.java
  src/main/java/com/mapu/domain/map/application/MapService.java
  src/main/java/com/mapu/domain/map/application/response/MapEditorListResponseDTO.java
  src/main/java/com/mapu/domain/map/application/response/MapEditorResponseDTO.java
  src/main/java/com/mapu/domain/map/dao/MapKeywordRepository.java
  src/main/java/com/mapu/domain/map/dao/MapRepository.java
  src/main/java/com/mapu/domain/map/dao/MapUserRoleRepository.java
  src/main/java/com/mapu/domain/map/domain/Map.java
  src/main/java/com/mapu/domain/map/domain/MapUserRole.java
  src/main/java/com/mapu/domain/map/exception/errcode/MapExceptionErrorCode.java
  src/main/java/com/mapu/domain/user/api/UserController.java
  src/main/java/com/mapu/domain/user/api/request/UserUpdateRequestDTO.java
  src/main/java/com/mapu/domain/user/application/UserService.java
  src/main/java/com/mapu/domain/user/dao/UserRepository.java
  src/main/java/com/mapu/domain/user/exception/errorcode/UserExceptionErrorCode.java
  src/main/resources/application.yml
Labels: 🛠 Feature, ✔Fix

#69 Feat(Home): 타유저정보가져오기 & Feat(Map): 북마크기능추가 & Fix(User): 회원휴면처리와로그인
  src/main/java/com/mapu/domain/map/api/MapController.java
  src/main/java/com/mapu/domain/map/application/MapService.java
  src/main/java/com/mapu/domain/map/dao/MapRepository.java
  src/main/java/com/mapu/domain/map/dao/MapUserBookmarkRepository.java
  src/main/java/com/mapu/domain/map/domain/MapUserBookmark.java
  src/main/java/com/mapu/domain/map/exception/errcode/MapExceptionErrorCode.java
  src/main/java/com/mapu/domain/user/api/UserController.java
  src/main/java/com/mapu/domain/user/api/request/SignInRequestDTO.java
  src/main/java/com/mapu/domain/user/application/UserService.java
  src/main/java/com/mapu/global/jwt/JwtUtil.java
Labels: 🛠 Feature, ✔Fix

#70 Fix(Map) : map entity imageUrl column 추가 & searchWord 검색어 키워드 추가
  src/main/java/com/mapu/domain/map/api/MapController.java
  src/main/java/com/mapu/domain/map/application/MapService.java
  src/main/java/com/mapu/domain/map/dao/MapRepository.java
  src/main/java/com/mapu/domain/map/domain/Map.java
Labels: 🛠 Feature, ✔Fix

#75 Feat: 66 get user page map data
  src/main/java/com/mapu/domain/user/api/UserController.java
  src/main/java/com/mapu/domain/user/application/UserService.java
  src/main/java/com/mapu/global/common/config/SecurityConfig.java
  src/main/java/com/mapu/global/jwt/JwtUtil.java
  src/main/java/com/mapu/global/jwt/exception/errorcode/JwtExceptionErrorCode.java
  src/main/java/com/mapu/global/jwt/filter/JwtExceptionFilter.java
  src/main/java/com/mapu/global/jwt/filter/JwtFilter.java
Labels: 🛠 Feature

#78 Feat: 유저페이지 지도데이터 조회
  src/main/java/com/mapu/domain/map/dao/MapRepository.java
  src/main/java/com/mapu/domain/map/dao/MapUserRoleRepository.java
  src/main/java/com/mapu/domain/user/api/UserController.java
  src/main/java/com/mapu/domain/user/application/UserService.java
  src/main/java/com/mapu/domain/user/application/response/UserPageMapParticipantsDTO.java
  src/main/java/com/mapu/domain/user/application/response/UserPageMapsDTO.java
  src/main/java/com/mapu/domain/user/application/response/UserPageMapsResponseDTO.java
  src/main/java/com/mapu/domain/user/dao/UserRepository.java
  src/main/java/com/mapu/domain/user/exception/errorcode/UserExceptionErrorCode.java
Labels: 🛠 Feature

#81 Fix: refresh-token samesite 문제 해결
  src/main/java/com/mapu/domain/user/application/UserService.java
  src/main/java/com/mapu/global/jwt/JwtUtil.java
  src/main/java/com/mapu/global/jwt/api/JwtController.java
  src/main/java/com/mapu/global/jwt/application/JwtService.java
  src/main/java/com/mapu/infra/oauth/application/OAuthService.java
Labels: ✔Fix

#82 Fix: /home/map/keyword permitAll 추가
  src/main/java/com/mapu/global/common/config/SecurityConfig.java
  src/main/java/com/mapu/global/jwt/filter/JwtFilter.java
Labels: ✔Fix
