Repository KUIT-MAPU/MAPU-Backend, pull requests merged in 2024-07, with the labels that each got.

#8 Fix: update cicd.yml
  .github/workflows/cicd.yml
Labels: ✔Fix, 💻 Infra

#10 Feat: apply GitHub actions cd
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  appspec.yml
  build.gradle
  scripts/deploy.sh
Labels: 🛠 Feature, 💻 Infra

#11 Docs: 로그 파일을 저장하도록 설정
  src/main/resources/application.yml
Labels: ✏️ Documentation, ✔Fix, 💻 Infra

#12 Fix: 로그 파일을 저장하도록 script 파일 수정
  scripts/deploy.sh
Labels: 🚨 Bug, ✔Fix

#13 Fix: 환경변수에 YML 파일을 넣고, application.yml을 덮어쓰도록 설정
  .github/workflows/cd.yml
  .gitignore
  src/main/resources/application.yml
Labels: 🚨 Bug, ✔Fix, 💻 Infra

#37 Feat: S3에 이미지 업로드 및 삭제
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/mapu/global/common/exception/handler/BaseExceptionHandler.java
  src/main/java/com/mapu/infra/s3/application/S3Service.java
  src/main/java/com/mapu/infra/s3/config/S3Config.java
  src/main/java/com/mapu/infra/s3/exception/AwsS3ErrorCode.java
  src/main/java/com/mapu/infra/s3/exception/AwsS3Exception.java
  src/main/java/com/mapu/infra/s3/exception/AwsS3ExceptionHandler.java
Labels: 🛠 Feature

#40 Feat(jwt): 사용자 인증을 위한 jwt 토큰 추가
  build.gradle
  src/main/java/com/mapu/domain/user/api/UserApi.java
  src/main/java/com/mapu/domain/user/application/UserService.java
  src/main/java/com/mapu/domain/user/application/response/SignUpResponseDTO.java
  src/main/java/com/mapu/domain/user/dao/UserRepository.java
  src/main/java/com/mapu/global/common/config/JpaConfig.java
  src/main/java/com/mapu/global/common/config/RedisRepositoryConfig.java
  src/main/java/com/mapu/global/common/config/SecurityConfig.java
  src/main/java/com/mapu/global/jwt/JwtFilter.java
  src/main/java/com/mapu/global/jwt/JwtReissueController.java
  src/main/java/com/mapu/global/jwt/JwtService.java
  src/main/java/com/mapu/global/jwt/JwtUtil.java
  src/main/java/com/mapu/global/jwt/dao/JwtRedisRepository.java
  src/main/java/com/mapu/global/jwt/domain/JwtRedis.java
  src/main/java/com/mapu/global/jwt/dto/JwtUserDto.java
  src/main/java/com/mapu/infra/oauth/OAuthLoginController.java
  src/main/resources/application.yml
Labels: 🛠 Feature, ✔Fix

#45 Fix: validator 적용안되는 문제 해결
  build.gradle
  src/main/java/com/mapu/domain/user/api/UserController.java
  src/main/java/com/mapu/domain/user/api/request/SignUpRequestDTO.java
  src/main/java/com/mapu/domain/user/application/UserService.java
  src/main/java/com/mapu/domain/user/exception/handler/UserExceptionHandler.java
  src/main/java/com/mapu/global/common/exception/handler/BaseExceptionHandler.java
Labels: ✔Fix

#46 Fix: signin/signup 성공 응답 수정
  src/main/java/com/mapu/domain/user/api/UserController.java
  src/main/java/com/mapu/domain/user/application/UserService.java
  src/main/java/com/mapu/domain/user/application/response/SignInResponseDTO.java
  src/main/java/com/mapu/domain/user/application/response/SignInUpResponseDTO.java
  src/main/java/com/mapu/domain/user/application/response/SignUpResponseDTO.java
  src/main/java/com/mapu/infra/oauth/application/OAuthService.java
Labels: 🛠 Feature

#43 Fix(OAuth): fix google login
  src/main/java/com/mapu/domain/user/domain/User.java
  src/main/java/com/mapu/infra/oauth/application/OAuthService.java
  src/main/java/com/mapu/infra/oauth/domain/OAuth.java
  src/main/java/com/mapu/infra/oauth/exception/errorcode/OAuthExceptionErrorCode.java
  src/main/java/com/mapu/infra/oauth/google/GoogleUserInfo.java
  src/main/java/com/mapu/infra/oauth/google/GoogleUserService.java
  src/main/java/com/mapu/infra/oauth/kakao/KakaoUserService.java
  src/main/resources/application.yml
Labels: ✔Fix

#48 Feat: JWTFilter에 액세스 토큰 검증 로직 추가
  src/main/java/com/mapu/MapuApplication.java
  src/main/java/com/mapu/domain/user/application/response/SignInResponseDTO.java
  src/main/java/com/mapu/domain/user/application/response/SignUpResponseDTO.java
  src/main/java/com/mapu/global/common/config/SecurityConfig.java
  src/main/java/com/mapu/global/common/domain/BaseEntity.java
  src/main/java/com/mapu/global/common/response/BaseErrorResponse.java
  src/main/java/com/mapu/global/jwt/application/JwtService.java
  src/main/java/com/mapu/global/jwt/exception/errorcode/JwtExceptionErrorCode.java
  src/main/java/com/mapu/global/jwt/filter/JwtExceptionFilter.java
  src/main/java/com/mapu/global/jwt/filter/JwtFilter.java
  src/main/java/com/mapu/global/jwt/filter/JwtLogoutFilter.java
  src/main/java/com/mapu/global/jwt/filter/handler/JwtLogoutHandler.java
  src/main/java/com/mapu/global/jwt/filter/handler/JwtLogoutSuccessHandler.java
Labels: 🛠 Feature, ✔Fix

#50 Feat: 유저 프로필 조회 및 수정
  src/main/java/com/mapu/domain/user/api/UserController.java
  src/main/java/com/mapu/domain/user/api/request/UserUpdateRequestDTO.java
  src/main/java/com/mapu/domain/user/application/UserService.java
  src/main/java/com/mapu/domain/user/application/response/UserInfoResponseDTO.java
  src/main/java/com/mapu/domain/user/application/response/UserUpdateResponseDTO.java
  src/main/java/com/mapu/domain/user/exception/errorcode/UserExceptionErrorCode.java
  src/main/java/com/mapu/global/common/response/BaseResponse.java
Labels: 🛠 Feature
